env:
  - GHC_VERSION=7.4.2  CABAL_VERSION=1.18
  - GHC_VERSION=7.6.3  CABAL_VERSION=1.18
  - GHC_VERSION=7.8.4  CABAL_VERSION=1.20
  - GHC_VERSION=7.10.1 CABAL_VERSION=1.22


before_install:
  - travis_retry sudo apt-add-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y ghc-$GHC_VERSION cabal-install-$CABAL_VERSION
  - export PATH=/opt/ghc/$GHC_VERSION/bin:/opt/cabal/$CABAL_VERSION/bin:$PATH

install:
  - travis_retry cabal update
  - (cd dbcleaner-core && cabal sandbox init)
  - (cd dbcleaner-core && travis_retry cabal install --only-dependencies --enable-tests)
  - (cd dbcleaner-postgresql-simple && cabal sandbox init)
  - (cd dbcleaner-postgresql-simple && cabal sandbox add-source ../dbcleaner-core)
  - (cd dbcleaner-postgresql-simple && travis_retry cabal install --only-dependencies --enable-tests)
  - (cd dbcleaner-hdbc && cabal sandbox init)
  - (cd dbcleaner-hdbc && cabal sandbox add-source ../dbcleaner-core)
  - (cd dbcleaner-hdbc && travis_retry cabal install --only-dependencies --enable-tests)

before_script:
  - createdb dbcleaner
  - psql dbcleaner < dbcleaner-postgresql-simple/test/schema.sql
  - createdb dbcleaner-hdbc
  - psql dbcleaner-hdbc < dbcleaner-hdbc/test/schema-postgresql.sql
  - sqlite3 dbcleaner-hdbc/dbcleaner-hdbc.db < dbcleaner-hdbc/test/schema-sqlite3.sql

script:
  - (cd dbcleaner-core && cabal configure --enable-tests)
  - (cd dbcleaner-core && cabal build) 
  - (cd dbcleaner-core && cabal test) 
  - (cd dbcleaner-postgresql-simple && cabal configure --enable-tests)
  - (cd dbcleaner-postgresql-simple && cabal build)
  - (cd dbcleaner-postgresql-simple && cabal test)
  - (cd dbcleaner-hdbc && cabal configure --enable-tests)
  - (cd dbcleaner-hdbc && cabal build)
  - (cd dbcleaner-hdbc && cabal test)
