---
language: haskell

ghc:
  - "8.2"

services:
  - postgresql

install:
  - cd dbcleaner-persistent-postgresql
  - cabal install --only-dependencies --enable-tests

script:
  - cd dbcleaner-persistent-postgresql
  - cabal configure --enable-tests
  - cabal build
  - cabal test
