---
language: haskell

services:
  - postgresql

ghc:
  - "8.2"
  - "8.0"

env:
  global:
    - PATH=/opt/happy/1.19.5/bin:$PATH
  matrix:
    - PACKAGEDIR="dbcleaner-persistent-postgresql"

addons:
  apt:
    packages:
      - happy-1.19.5

before_install:
  - cd $PACKAGEDIR
  - cabal sandbox init
  - cabal sandbox add-source ../dbcleaner

before_script:
  - createdb dbcleaner
