---
language: haskell

services:
  - postgresql

ghc:
  - "8.2"

env:
  - PACKAGEDIR="dbcleaner-persistent-postgresql"

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - happy-1.19.5

before_install:
  - cd $PACKAGEDIR
  - cabal sandbox init
  - cabal sandbox add-source ../dbcleaner
