---
name:     dbcleaner-persistent-postgresql
version:  0.1.3

dependencies:
  - base >= 4.7 && < 5
  - exceptions
  - persistent

library:
  source-dirs: src
  dependencies:
    - dbcleaner
    - text

tests:
  spec:
    main:         Spec.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dbcleaner-persistent-postgresql
      - hspec
      - monad-logger
      - persistent-postgresql
      - persistent-template
