---
name:     dbcleaner-postgresql-simple
version:  0.1.3

dependencies:
  - base >= 4.7 && < 5
  - exceptions
  - mtl
  - postgresql-simple

library:
  source-dirs: src
  dependencies:
    - dbcleaner

tests:
  spec:
    main:         Spec.hs
    source-dirs:  test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dbcleaner-postgresql-simple
      - hspec
